function [ par ] = calcPitzerParameter( c , P , T )
% Input 1-D array with all 10 interaction parameters in order
% Output resulting summation of parameters
% Vectorization already supported

% EQ 7 in Duan et al. (1992)
par =   c(1) ...
        + c(2).*T ...
        + c(3)./T ...
        + c(4).*T.^2 ...
        + c(5)./(680 - T) ...
        + c(6).*P ...
        + c(7).*P.*log(T) ...
        + c(8).*P./T ...
        + c(9).*P/(680 - T) ...
        + c(10).*P^2./T; 

end

